import type { Property } from "@/types/property";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "cobertura-duplex-recreio-4-suites",
    code: "JBRB502558",
    title: "Cobertura Duplex 4 Suítes com Piscina e Churrasqueira",
    description:
      "Exuberante cobertura duplex no Recreio dos Bandeirantes com vista panorâmica para o mar. Acabamentos italianos, piscina privativa aquecida, heliponto e concierge 24h.",
    type: "cobertura",
    status: "venda",
    tag: "SIGNATURE",
    price: 6_800_000,
    condoFee: 3200,
    iptu: 1800,
    address: {
      street: "Avenida Lúcio Costa",
      number: "7800",
      neighborhood: "Recreio dos Bandeirantes",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 420,
      usableArea: 380,
      bedrooms: 4,
      suites: 4,
      bathrooms: 6,
      parkingSpots: 4,
      hasPool: true,
      hasHelipad: true,
      hasConcierge: true,
      hasSeaView: true,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
        alt: "Sala de estar com vista panorâmica",
        width: 1200,
        height: 800,
        blurDataUrl: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgUEB//EACIQAAIBAwUBAQAAAAAAAAAAAAECAwAEBRIhMVFh0f/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCW3nFrPaKs0VvNMiHJVkzx96kW2+W8kKloixdTjzjvVSigHDajf//Z",
      },
      {
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
        alt: "Piscina privativa",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag1",
      name: "Rodrigo Monteiro",
      phone: "5521999887766",
      whatsapp: "5521999887766",
      creci: "CRECI-RJ 12345",
    },
    featured: true,
    publishedAt: "2024-01-15",
    updatedAt: "2024-05-01",
  },
  {
    id: "2",
    slug: "penthouse-ipanema-vista-mar",
    code: "IPT001",
    title: "Penthouse Exclusiva em Ipanema com Vista Mar 360°",
    description:
      "Penthouse única com terraço de 200m² e vista total para o mar de Ipanema. Design assinado, spa privativo, adega climatizada e segurança máxima.",
    type: "penthouse",
    status: "venda",
    tag: "EXCLUSIVO",
    price: 18_500_000,
    condoFee: 8500,
    iptu: 5200,
    address: {
      street: "Rua Visconde de Pirajá",
      number: "414",
      neighborhood: "Ipanema",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 680,
      usableArea: 580,
      bedrooms: 5,
      suites: 5,
      bathrooms: 8,
      parkingSpots: 6,
      hasPool: true,
      hasGym: true,
      hasSauna: true,
      hasSeaView: true,
      hasConcierge: true,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80",
        alt: "Terraço com vista para Ipanema",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag2",
      name: "Carolina Ferreira",
      phone: "5521988776655",
      whatsapp: "5521988776655",
      creci: "CRECI-RJ 23456",
    },
    featured: true,
    publishedAt: "2024-02-10",
    updatedAt: "2024-05-01",
  },
  {
    id: "3",
    slug: "apartamento-barra-da-tijuca-3-suites",
    code: "BAR003",
    title: "Apartamento Alto Padrão 3 Suítes na Barra da Tijuca",
    description:
      "Apartamento sofisticado em condomínio fechado na Barra da Tijuca. Lazer completo, segurança 24h e fácil acesso às principais vias.",
    type: "apartamento",
    status: "venda",
    tag: "DESTAQUE",
    price: 1_950_000,
    condoFee: 1800,
    iptu: 650,
    address: {
      street: "Avenida das Américas",
      number: "3434",
      neighborhood: "Barra da Tijuca",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 186,
      usableArea: 166,
      bedrooms: 3,
      suites: 3,
      bathrooms: 5,
      parkingSpots: 2,
      hasPool: true,
      hasGym: true,
      petFriendly: true,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
        alt: "Sala de estar moderna",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag1",
      name: "Rodrigo Monteiro",
      phone: "5521999887766",
      whatsapp: "5521999887766",
      creci: "CRECI-RJ 12345",
    },
    featured: false,
    publishedAt: "2024-03-05",
    updatedAt: "2024-05-01",
  },
  {
    id: "4",
    slug: "casa-condominio-recreio-5-suites",
    code: "CAS004",
    title: "Casa em Condomínio Fechado 5 Suítes Recreio",
    description:
      "Mansão contemporânea em condomínio de altíssimo padrão com jardim tropical, piscina e churrasqueira gourmet.",
    type: "casa",
    status: "venda",
    tag: "NOVO",
    price: 9_200_000,
    condoFee: 2800,
    iptu: 3100,
    address: {
      street: "Estrada dos Bandeirantes",
      number: "22000",
      neighborhood: "Recreio dos Bandeirantes",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 950,
      usableArea: 780,
      bedrooms: 5,
      suites: 5,
      bathrooms: 7,
      parkingSpots: 6,
      hasPool: true,
      hasGym: true,
      hasSauna: true,
      petFriendly: true,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
        alt: "Fachada da residência",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag3",
      name: "Marcus Oliveira",
      phone: "5521977665544",
      whatsapp: "5521977665544",
      creci: "CRECI-RJ 34567",
    },
    featured: true,
    publishedAt: "2024-04-01",
    updatedAt: "2024-05-01",
  },
  {
    id: "5",
    slug: "apartamento-leblon-2-suites",
    code: "LEB005",
    title: "Apartamento de Luxo 2 Suítes no Leblon",
    description:
      "Apartamento totalmente renovado no coração do Leblon. A dois quarteirões da praia com acabamento impecável.",
    type: "apartamento",
    status: "venda",
    tag: "DESTAQUE",
    price: 3_800_000,
    condoFee: 2200,
    iptu: 1100,
    address: {
      street: "Rua Dias Ferreira",
      number: "190",
      neighborhood: "Leblon",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 120,
      usableArea: 110,
      bedrooms: 2,
      suites: 2,
      bathrooms: 3,
      parkingSpots: 2,
      hasSeaView: false,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
        alt: "Sala de jantar sofisticada",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag2",
      name: "Carolina Ferreira",
      phone: "5521988776655",
      whatsapp: "5521988776655",
      creci: "CRECI-RJ 23456",
    },
    featured: false,
    publishedAt: "2024-04-20",
    updatedAt: "2024-05-01",
  },
  {
    id: "6",
    slug: "cobertura-sao-conrado-4-suites",
    code: "SCO006",
    title: "Cobertura São Conrado 4 Suítes Vista Pedra da Gávea",
    description:
      "Cobertura espetacular com terraço panorâmico e vista incomparável para a Pedra da Gávea e o mar.",
    type: "cobertura",
    status: "venda",
    tag: "SIGNATURE",
    price: 12_500_000,
    condoFee: 6000,
    iptu: 3800,
    address: {
      street: "Estrada da Gávea",
      number: "899",
      neighborhood: "São Conrado",
      city: "Rio de Janeiro",
      state: "RJ",
    },
    specs: {
      totalArea: 540,
      usableArea: 460,
      bedrooms: 4,
      suites: 4,
      bathrooms: 6,
      parkingSpots: 4,
      hasPool: true,
      hasSeaView: true,
      hasConcierge: true,
    },
    images: [
      {
        url: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1200&q=80",
        alt: "Terraço com vista panorâmica",
        width: 1200,
        height: 800,
      },
    ],
    agent: {
      id: "ag1",
      name: "Rodrigo Monteiro",
      phone: "5521999887766",
      whatsapp: "5521999887766",
      creci: "CRECI-RJ 12345",
    },
    featured: true,
    publishedAt: "2024-05-01",
    updatedAt: "2024-05-01",
  },
];
